// <auto-generated />
using CampSleepway_TeamGaJoL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampSleepway_TeamGaJoL.Migrations
{
    [DbContext(typeof(CampSleepawayContext))]
    [Migration("20231215111555_classes updated")]
    partial class classesupdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Cabin", b =>
                {
                    b.Property<int>("CabinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CabinId"));

                    b.HasKey("CabinId");

                    b.ToTable("Cabins");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Camper", b =>
                {
                    b.HasBaseType("CampSleepway_TeamGaJoL.Person");

                    b.Property<int>("CamperId")
                        .HasColumnType("int");

                    b.Property<int>("endDate")
                        .HasColumnType("int");

                    b.Property<int>("startDate")
                        .HasColumnType("int");

                    b.ToTable("Persons", t =>
                        {
                            t.Property("CamperId")
                                .HasColumnName("CamperId1");
                        });

                    b.HasDiscriminator().HasValue("Camper");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Councelor", b =>
                {
                    b.HasBaseType("CampSleepway_TeamGaJoL.Person");

                    b.Property<int>("CouncelorId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Councelor");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.NextOfKin", b =>
                {
                    b.HasBaseType("CampSleepway_TeamGaJoL.Person");

                    b.Property<int>("CamperId")
                        .HasColumnType("int");

                    b.Property<int>("NextOfKinId")
                        .HasColumnType("int");

                    b.HasIndex("CamperId");

                    b.HasDiscriminator().HasValue("NextOfKin");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.NextOfKin", b =>
                {
                    b.HasOne("CampSleepway_TeamGaJoL.Camper", "Camper")
                        .WithMany()
                        .HasForeignKey("CamperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camper");
                });
#pragma warning restore 612, 618
        }
    }
}
