// <auto-generated />
using System;
using CampSleepway_TeamGaJoL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampSleepway_TeamGaJoL.Migrations
{
    [DbContext(typeof(CampSleepawayContext))]
<<<<<<<< HEAD:CampSleepway_TeamGaJoL/Migrations/20231215134551_classes.Designer.cs
    [Migration("20231215134551_classes")]
    partial class classes
========
    [Migration("20231218151725_wee")]
    partial class wee
>>>>>>>> 8c22dd527880a172fb917a8bb99f0c58881d211d:CampSleepway_TeamGaJoL/Migrations/20231218151725_wee.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Cabin", b =>
                {
                    b.Property<int>("CabinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CabinId"));

                    b.HasKey("CabinId");

                    b.ToTable("Cabins");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

<<<<<<<< HEAD:CampSleepway_TeamGaJoL/Migrations/20231215134551_classes.Designer.cs
                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

========
>>>>>>>> 8c22dd527880a172fb917a8bb99f0c58881d211d:CampSleepway_TeamGaJoL/Migrations/20231218151725_wee.Designer.cs
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

<<<<<<<< HEAD:CampSleepway_TeamGaJoL/Migrations/20231215134551_classes.Designer.cs
                    b.ToTable("Person");
========
                    b.ToTable("Persons", (string)null);
>>>>>>>> 8c22dd527880a172fb917a8bb99f0c58881d211d:CampSleepway_TeamGaJoL/Migrations/20231218151725_wee.Designer.cs

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Camper", b =>
                {
                    b.HasBaseType("CampSleepway_TeamGaJoL.Person");

<<<<<<<< HEAD:CampSleepway_TeamGaJoL/Migrations/20231215134551_classes.Designer.cs
                    b.Property<int>("CabinId")
                        .HasColumnType("int");

                    b.Property<int>("CamperId")
                        .HasColumnType("int");

                    b.Property<int>("endDate")
                        .HasColumnType("int");

                    b.Property<int>("startDate")
                        .HasColumnType("int");

                    b.HasIndex("CabinId");

                    b.ToTable("Person", t =>
                        {
                            t.Property("CabinId")
                                .HasColumnName("Camper_CabinId");

                            t.Property("CamperId")
                                .HasColumnName("CamperId1");
                        });

                    b.HasDiscriminator().HasValue("Camper");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Councelor", b =>
                {
                    b.HasBaseType("CampSleepway_TeamGaJoL.Person");

                    b.Property<int>("CabinId")
                        .HasColumnType("int");

                    b.Property<int>("CouncelorId")
                        .HasColumnType("int");

                    b.HasIndex("CabinId")
                        .IsUnique()
                        .HasFilter("[CabinId] IS NOT NULL");

                    b.ToTable("Person");

                    b.HasDiscriminator().HasValue("Councelor");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.NextOfKin", b =>
                {
                    b.HasBaseType("CampSleepway_TeamGaJoL.Person");

========
                    b.Property<int?>("CabinId")
                        .HasColumnType("int");

>>>>>>>> 8c22dd527880a172fb917a8bb99f0c58881d211d:CampSleepway_TeamGaJoL/Migrations/20231218151725_wee.Designer.cs
                    b.Property<int>("CamperId")
                        .HasColumnType("int");

                    b.Property<int>("EndDate")
                        .HasColumnType("int");

                    b.Property<int>("StartDate")
                        .HasColumnType("int");

<<<<<<<< HEAD:CampSleepway_TeamGaJoL/Migrations/20231215134551_classes.Designer.cs
                    b.ToTable("Person");

                    b.HasDiscriminator().HasValue("NextOfKin");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Camper", b =>
                {
                    b.HasOne("CampSleepway_TeamGaJoL.Cabin", "Cabin")
                        .WithMany("Campers")
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabin");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Councelor", b =>
                {
                    b.HasOne("CampSleepway_TeamGaJoL.Cabin", "Cabin")
                        .WithOne("Councelor")
                        .HasForeignKey("CampSleepway_TeamGaJoL.Councelor", "CabinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabin");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.NextOfKin", b =>
                {
                    b.HasOne("CampSleepway_TeamGaJoL.Camper", "Camper")
                        .WithMany("NextOfKins")
                        .HasForeignKey("CamperId")
========
                    b.HasIndex("CabinId");

                    b.ToTable("Campers", (string)null);
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Counselor", b =>
                {
                    b.HasBaseType("CampSleepway_TeamGaJoL.Person");

                    b.Property<int>("CounselorId")
                        .HasColumnType("int");

                    b.Property<int>("EndDate")
                        .HasColumnType("int");

                    b.Property<int>("StartDate")
                        .HasColumnType("int");

                    b.ToTable("Councelors", (string)null);
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Camper", b =>
                {
                    b.HasOne("CampSleepway_TeamGaJoL.Cabin", null)
                        .WithMany("Campers")
                        .HasForeignKey("CabinId");

                    b.HasOne("CampSleepway_TeamGaJoL.Person", null)
                        .WithOne()
                        .HasForeignKey("CampSleepway_TeamGaJoL.Camper", "Id")
>>>>>>>> 8c22dd527880a172fb917a8bb99f0c58881d211d:CampSleepway_TeamGaJoL/Migrations/20231218151725_wee.Designer.cs
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Counselor", b =>
                {
                    b.HasOne("CampSleepway_TeamGaJoL.Person", null)
                        .WithOne()
                        .HasForeignKey("CampSleepway_TeamGaJoL.Counselor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Cabin", b =>
                {
                    b.Navigation("Campers");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Cabin", b =>
                {
                    b.Navigation("Campers");

                    b.Navigation("Councelor")
                        .IsRequired();
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Camper", b =>
                {
                    b.Navigation("NextOfKins");
                });
#pragma warning restore 612, 618
        }
    }
}
