// <auto-generated />
using System;
using CampSleepway_TeamGaJoL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampSleepway_TeamGaJoL.Migrations
{
    [DbContext(typeof(CampSleepawayContext))]
    [Migration("20231220143531_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Cabin", b =>
                {
                    b.Property<int>("CabinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CabinId"));

                    b.Property<int>("CouncelorId")
                        .HasColumnType("int");

                    b.HasKey("CabinId");

                    b.HasIndex("CouncelorId");

                    b.ToTable("Cabins");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Camper", b =>
                {
                    b.HasBaseType("CampSleepway_TeamGaJoL.Person");

                    b.Property<int?>("CabinId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("CabinId");

                    b.ToTable("Campers", (string)null);
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Councelor", b =>
                {
                    b.HasBaseType("CampSleepway_TeamGaJoL.Person");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.ToTable("Councelors", (string)null);
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.NextOfKin", b =>
                {
                    b.HasBaseType("CampSleepway_TeamGaJoL.Person");

                    b.Property<int?>("CamperId")
                        .HasColumnType("int");

                    b.Property<int?>("CouncelorId")
                        .HasColumnType("int");

                    b.HasIndex("CamperId");

                    b.HasIndex("CouncelorId");

                    b.ToTable("NextOfKins", (string)null);
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Cabin", b =>
                {
                    b.HasOne("CampSleepway_TeamGaJoL.Councelor", "Councelor")
                        .WithMany()
                        .HasForeignKey("CouncelorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Councelor");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Camper", b =>
                {
                    b.HasOne("CampSleepway_TeamGaJoL.Cabin", null)
                        .WithMany("Campers")
                        .HasForeignKey("CabinId");

                    b.HasOne("CampSleepway_TeamGaJoL.Person", null)
                        .WithOne()
                        .HasForeignKey("CampSleepway_TeamGaJoL.Camper", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Councelor", b =>
                {
                    b.HasOne("CampSleepway_TeamGaJoL.Person", null)
                        .WithOne()
                        .HasForeignKey("CampSleepway_TeamGaJoL.Councelor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.NextOfKin", b =>
                {
                    b.HasOne("CampSleepway_TeamGaJoL.Camper", "Camper")
                        .WithMany("NextofKins")
                        .HasForeignKey("CamperId");

                    b.HasOne("CampSleepway_TeamGaJoL.Councelor", "Councelor")
                        .WithMany("NextOfKins")
                        .HasForeignKey("CouncelorId");

                    b.HasOne("CampSleepway_TeamGaJoL.Person", null)
                        .WithOne()
                        .HasForeignKey("CampSleepway_TeamGaJoL.NextOfKin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camper");

                    b.Navigation("Councelor");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Cabin", b =>
                {
                    b.Navigation("Campers");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Camper", b =>
                {
                    b.Navigation("NextofKins");
                });

            modelBuilder.Entity("CampSleepway_TeamGaJoL.Councelor", b =>
                {
                    b.Navigation("NextOfKins");
                });
#pragma warning restore 612, 618
        }
    }
}
